import React from "react";
import Header from "./Header";
import Footer from "./Footer";

const TermsAndConditions = () => {
  return (
    <div>
      <Header></Header>
      <div className="min-h-screen bg-gray-100 text-gray-800 px-4 py-10">
        <div className="max-w-3xl mx-auto bg-white shadow-xl rounded-xl p-8">
          <h1 className="text-3xl font-bold mb-6 text-center">
            Terms and Conditions
          </h1>
          <p className="text-sm text-gray-500 mb-6 text-center">
            Effective Date: July 10, 2025
          </p>

          <section className="mb-6">
            <p>
              Welcome to our KS BMI App. By using this website, you
              agree to the following terms and conditions. If you do not agree
              with any part of these terms, please do not use the site.
            </p>
          </section>

          <section className="mb-6">
            <h2 className="text-xl font-semibold mb-2">
              1. Use of the Website
            </h2>
            <p>
              This website is intended for informational and educational
              purposes only. The BMI (Body Mass Index) calculator is a general
              tool and should not be treated as a substitute for professional
              medical advice, diagnosis, or treatment.
            </p>
          </section>

          <section className="mb-6">
            <h2 className="text-xl font-semibold mb-2">2. No Medical Advice</h2>
            <p>
              The content and results provided on this site do not constitute
              medical advice. Always consult a qualified healthcare professional
              before making any health-related decisions.
            </p>
          </section>

          <section className="mb-6">
            <h2 className="text-xl font-semibold mb-2">
              3. Accuracy of Information
            </h2>
            <p>
              We aim to keep the content and calculations as accurate as
              possible. However, we do not guarantee the accuracy, reliability,
              or completeness of any information or results generated by the BMI
              calculator.
            </p>
          </section>

          <section className="mb-6">
            <h2 className="text-xl font-semibold mb-2">
              4. Google Ads and Third-Party Advertising
            </h2>
            <p>
              This website serves Google Ads. Third-party vendors, including
              Google, use cookies to serve ads based on your prior visits to
              this website or other websites. These ads help support and
              maintain the free tools offered on this site. We do not control
              the content of these ads.
            </p>
          </section>

          <section className="mb-6">
            <h2 className="text-xl font-semibold mb-2">
              5. User Responsibilities
            </h2>
            <p>
              You agree to use this website only for lawful purposes and in a
              way that does not infringe the rights of others or restrict their
              use of the site.
            </p>
          </section>

          <section className="mb-6">
            <h2 className="text-xl font-semibold mb-2">
              6. Limitation of Liability
            </h2>
            <p>
              We are not liable for any damages or losses arising from the use
              of this website or reliance on any content provided. All use is at
              your own risk.
            </p>
          </section>

          <section className="mb-6">
            <h2 className="text-xl font-semibold mb-2">7. Changes to Terms</h2>
            <p>
              We reserve the right to change or update these terms at any time
              without prior notice. It is your responsibility to review this
              page periodically for any updates.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">8. Contact Us</h2>
            <p>
              If you have any questions about these Terms and Conditions, you
              may contact us using the contact form on our website.
            </p>
          </section>
        </div>
      </div>
      <Footer></Footer>
    </div>
  );
};

export default TermsAndConditions;
